name: Run Dependabot

on:
  workflow_dispatch:   # permite ejecutarlo manualmente desde la pesta√±a Actions

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot
        uses: dependabot/fetch-metadata@v1
