version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"   # ejecución una vez por semana
    open-pull-requests-limit: 0   # evita que Dependabot abra PRs automáticos
    commit-message:
      prefix: "deps"
    labels:
      - "dependabot"
    reviewers:
      - "Jesusdio2"
